spring.application.name=league-control
logging.pattern.dateformat=yyyy-MM-dd
#spring.profiles.active=populated
logging.level.com.iwaconsolti =DEBUG
league.teams.limit=10

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
