# Liga de Futbol - Partidos
match.matchconfiglist[0].idmatch=1
match.matchconfiglist[0].idleague=1
match.matchconfiglist[0].localteam.idteam=1
match.matchconfiglist[0].localteam.teamname=pablitosfc
match.matchconfiglist[0].visitteam.idteam=2
match.matchconfiglist[0].visitteam.teamname=franciscofc
match.matchconfiglist[0].goallocal=1
match.matchconfiglist[0].goalVisit=1

match.matchconfiglist[1].idmatch=2
match.matchconfiglist[1].idleague=1
match.matchconfiglist[1].localteam.idteam=2
match.matchconfiglist[1].localteam.teamname=franciscofc
match.matchconfiglist[1].visitteam.idteam=1
match.matchconfiglist[1].visitteam.teamname=pablitosfc
match.matchconfiglist[1].goallocal=2
match.matchconfiglist[1].goalVisit=3

# Liga de Basquetball - Partidos
match.matchconfiglist[2].idmatch=1
match.matchconfiglist[2].idleague=2
match.matchconfiglist[2].localteam.idteam=1
match.matchconfiglist[2].localteam.teamname=gatos
match.matchconfiglist[2].visitteam.idteam=2
match.matchconfiglist[2].visitteam.teamname=perros
match.matchconfiglist[2].goallocal=1
match.matchconfiglist[2].goalVisit=1

match.matchconfiglist[3].idmatch=2
match.matchconfiglist[3].idleague=2
match.matchconfiglist[3].localteam.idteam=2
match.matchconfiglist[3].localteam.teamname=perros
match.matchconfiglist[3].visitteam.idteam=1
match.matchconfiglist[3].visitteam.teamname=gatos
match.matchconfiglist[3].goallocal=2
match.matchconfiglist[3].goalVisit=3

# Equipos de la Liga de Futbol
teams.teamsconfiglist[0].idteam=1
teams.teamsconfiglist[0].idLeague=1
teams.teamsconfiglist[0].teamname=pablitosfc

teams.teamsconfiglist[1].idteam=2
teams.teamsconfiglist[1].idLeague=1
teams.teamsconfiglist[1].teamname=franciscofc

# Equipos de la Liga de Basquetball
teams.teamsconfiglist[2].idteam=1
teams.teamsconfiglist[2].idLeague=2
teams.teamsconfiglist[2].teamname=gatos

teams.teamsconfiglist[3].idteam=2
teams.teamsconfiglist[3].idLeague=2
teams.teamsconfiglist[3].teamname=perros

# Jugadores de la Liga de Futbol
players.playerconfiglist[0].idpLayer=1
players.playerconfiglist[0].idleague=1
players.playerconfiglist[0].idteam=1
players.playerconfiglist[0].nameplayer=juan

players.playerconfiglist[1].idpLayer=2
players.playerconfiglist[1].idleague=1
players.playerconfiglist[1].idteam=1
players.playerconfiglist[1].nameplayer=carlos

# Jugadores de la Liga de Basquetball
players.playerconfiglist[2].idpLayer=3
players.playerconfiglist[2].idleague=2
players.playerconfiglist[2].idteam=1
players.playerconfiglist[2].nameplayer=juan

players.playerconfiglist[3].idpLayer=4
players.playerconfiglist[3].idleague=2
players.playerconfiglist[3].idteam=2
players.playerconfiglist[3].nameplayer=carlos
