# Liga de Futbol - Partidos
match.lista[0].idmatch=1
match.lista[0].idleague=1
match.lista[0].localteam.idteam=1
match.lista[0].localteam.teamname=pablitosfc
match.lista[0].visitteam.idteam=2
match.lista[0].visitteam.teamname=franciscofc
match.lista[0].goallocal=1
match.lista[0].goalVisit=1

match.lista[1].idmatch=2
match.lista[1].idleague=1
match.lista[1].localteam.idteam=2
match.lista[1].localteam.teamname=franciscofc
match.lista[1].visitteam.idteam=1
match.lista[1].visitteam.teamname=pablitosfc
match.lista[1].goallocal=2
match.lista[1].goalVisit=3

# Liga de Basquetball - Partidos
match.lista[2].idmatch=1
match.lista[2].idleague=2
match.lista[2].localteam.idteam=1
match.lista[2].localteam.teamname=gatos
match.lista[2].visitteam.idteam=2
match.lista[2].visitteam.teamname=perros
match.lista[2].goallocal=1
match.lista[2].goalVisit=1

match.lista[3].idmatch=2
match.lista[3].idleague=2
match.lista[3].localteam.idteam=2
match.lista[3].localteam.teamname=perros
match.lista[3].visitteam.idteam=1
match.lista[3].visitteam.teamname=gatos
match.lista[3].goallocal=2
match.lista[3].goalVisit=3

# Equipos de la Liga de Futbol
teams.lista[0].idteam=1
teams.lista[0].idLeague=1
teams.lista[0].teamname=pablitosfc

teams.lista[1].idteam=2
teams.lista[1].idLeague=1
teams.lista[1].teamname=franciscofc

# Equipos de la Liga de Basquetball
teams.lista[2].idteam=1
teams.lista[2].idLeague=2
teams.lista[2].teamname=gatos

teams.lista[3].idteam=2
teams.lista[3].idLeague=2
teams.lista[3].teamname=perros

# Jugadores de la Liga de Futbol
players.lista[0].idpLayer=1
players.lista[0].idleague=1
players.lista[0].idteam=1
players.lista[0].nameplayer=juan

players.lista[1].idpLayer=2
players.lista[1].idleague=1
players.lista[1].idteam=1
players.lista[1].nameplayer=carlos

players.lista[2].idpLayer=3
players.lista[2].idleague=2
players.lista[2].idteam=1
players.lista[2].nameplayer=juan

players.lista[3].idpLayer=4
players.lista[3].idleague=2
players.lista[3].idteam=2
players.lista[3].nameplayer=carlos
