# Liga de Futbol
league.lista[0].idLeague=1
league.lista[0].nombre=futbol

# Equipos de la Liga de Futbol
league.lista[0].equipos[0].id=1
league.lista[0].equipos[0].idLiga=1
league.lista[0].equipos[0].nombre=pablitosfc
league.lista[0].equipos[0].jugadores[0].idJugador=1
league.lista[0].equipos[0].jugadores[0].idLiga=1
league.lista[0].equipos[0].jugadores[0].idEquipo=1
league.lista[0].equipos[0].jugadores[0].nombre=juan

league.lista[0].equipos[1].id=2
league.lista[0].equipos[1].idLiga=1
league.lista[0].equipos[1].nombre=franciscofc
league.lista[0].equipos[1].jugadores[0].idJugador=2
league.lista[0].equipos[1].jugadores[0].idLiga=1
league.lista[0].equipos[1].jugadores[0].idEquipo=2
league.lista[0].equipos[1].jugadores[0].nombre=carlos

# Partidos de la Liga de Futbol
league.lista[0].partidos[0].idPartido=1
league.lista[0].partidos[0].idLiga=1
league.lista[0].partidos[0].equipoLocal.id=1
league.lista[0].partidos[0].equipoLocal.nombre=pablitosfc
league.lista[0].partidos[0].equipoVisitante.id=2
league.lista[0].partidos[0].equipoVisitante.nombre=franciscofc
league.lista[0].partidos[0].golesLocal=1
league.lista[0].partidos[0].golesVisitante=1

# Liga de Basquetball
league.lista[1].idLeague=2
league.lista[1].nombre=basquetball

# Equipos de la Liga de Basquetball
league.lista[1].equipos[0].id=1
league.lista[1].equipos[0].idLiga=2
league.lista[1].equipos[0].nombre=gatos
league.lista[1].equipos[0].jugadores[0].idJugador=1
league.lista[1].equipos[0].jugadores[0].idLiga=2
league.lista[1].equipos[0].jugadores[0].idEquipo=1
league.lista[1].equipos[0].jugadores[0].nombre=juan

league.lista[1].equipos[1].id=2
league.lista[1].equipos[1].idLiga=2
league.lista[1].equipos[1].nombre=perros
league.lista[1].equipos[1].jugadores[0].idJugador=2
league.lista[1].equipos[1].jugadores[0].idLiga=2
league.lista[1].equipos[1].jugadores[0].idEquipo=2
league.lista[1].equipos[1].jugadores[0].nombre=carlos

# Partidos de la Liga de Basquetball
league.lista[1].partidos[0].idPartido=1
league.lista[1].partidos[0].idLiga=2
league.lista[1].partidos[0].equipoLocal.id=1
league.lista[1].partidos[0].equipoLocal.nombre=gatos
league.lista[1].partidos[0].equipoVisitante.id=2
league.lista[1].partidos[0].equipoVisitante.nombre=perros
league.lista[1].partidos[0].golesLocal=1
league.lista[1].partidos[0].golesVisitante=1
