spring.application.name=league-control
spring.profiles.active=default
league.max-teams=10

# Configuración de la base de datos H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

# Mostrar consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true